name: uploader
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.2.1+1
  file_picker: ^6.0.0
  loading_indicator: ^3.1.0
  
  flutter_bounceable: ^1.1.0
  pretty_dio_logger: ^1.3.1
  path: ^1.8.2
  path_provider: ^2.0.11
  flutter:
    sdk: flutter
  api:
    path: /users/thf/Apps_Flutter_Packages/api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
